### ISSUE TITLE
Support gvim and terminal with white background…

### ISSUE THREAD

**Issue by victornoel** [vim-dist/webvim#19]
Hi,

I have a terminal with a white background and it is impossible to read most of what webvim shows because there is a big use of very light colors…

It is the same in gvim!

**Comment by victornoel** [comment]
Note that I added "set background=light" in local.vim, but it's not enough, there is still many text difficult to read…

**Comment by krampstudio** [comment]
Yes, right now the color theme is https://github.com/goatslacker/mango.vim so it means I would need to add another one for light backgrounds.

**Comment by victornoel** [comment]
Maybe it could be interesting to provide at least a dark and a light one, and simple instructions to switch :)

**Comment by krampstudio** [comment]
Sure, It's what I was thinking. Do you have some propositions for the light color scheme ?

**Comment by victornoel** [comment]
Nop, I was doing a quick search and found that one: http://ethanschoonover.com/solarized/vim-colors-solarized but it actually support much more combinations.
It seems to be recommended by people, but I haven't even tried it yet :) (I'm new to vim tweaking)

**Comment by krampstudio** [comment]
Looking at this issue, I've found the Lucius color sheme that seems to be a good compromise and fit with most situation : https://github.com/jonathanfilip/lucius
