### ISSUE TITLE
Use local eslint when available

### ISSUE THREAD

**Issue by SebastienElet** [vim-dist/webvim#20]
When you work on a project with eslint as dev-dependency, it's better to use it instead of using global one.

I use the fallowing vimL to do the job : 
```viml
let g:local_eslint = finddir('node_modules', '.;') . '/.bin/eslint'
if matchstr(local_eslint, "^\/\\w") == ''
    let g:local_eslint = getcwd() . "/" . local_eslint
endif
if executable(local_eslint)
    let g:syntastic_javascript_eslint_exec = local_eslint
endif
```

**Comment by krampstudio** [comment]
Yes, it could be to https://github.com/krampstudio/webvim/blob/master/plugins/config.vim#L79

**Comment by huangyingjie** [comment]
hello @SebastienElet , I think this is better when node_modules are nested.
    " get eslintrc path
    let eslintrcpath = findfile('.eslintrc', '.;')
    autocmd FileType javascript let b:syntastic_checkers = eslintrcpath != '' ? ['eslint'] : ['jshint']
    " find eslint beside eslintrcpath
    let local_eslint = substitute(eslintrcpath, ".eslintrc", "", "") . "node_modules" . '/.bin/eslint'
    if executable(local_eslint)
        let g:syntastic_javascript_eslint_exec = local_eslint
    endif

**Comment by stephanebachelier** [comment]
@SebastienElet I think you should only need to update the env `PATH` to use `./node_modules/.bin`. 

```bash
export PATH=./node_modules/.bin:$PATH;
```

It will works for any editor or project you use.
