### ISSUE TITLE
PaperColor.vim not installed by webvim installer

### ISSUE THREAD

**Issue by tla-dev** [vim-dist/webvim#40]
I just did a fresh installation of WebVim on fedora 24.
The PaperColor.vim was not installed in ~/.vim/colors/ by the WebVim install process.
I downloaded and copy PaperColor.vim manually in ~/.vim/colors/ and it works.

**Comment by krampstudio** [comment]
Thank you for the report. I forgot to add the symlink. This should be fixed on master.
