### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by krampstudio** [vim-dist/webvim#46]
This was done by myself : http://webvim.org/images/WebVim.svg but isn't really sexy...

**Comment by Gajit** [comment]
![webvim](https://cloud.githubusercontent.com/assets/1156428/25793681/38b6a08e-3393-11e7-8ff7-d876015744ab.png)
I know I sent a PR for this a couple of days back but had to mess with it when I revisited it the next day. Let me know if you would want to use it and I can re-pull.

**Comment by krampstudio** [comment]
The previous you made was great, this one is even better !!! Let's use this one. 
You made my day!

**Comment by Gajit** [comment]
Glad you like it, I re submitted the PR.

**Comment by krampstudio** [comment]
The brand new logo has been integrated to http://webvim.org/
