### ISSUE TITLE
any key into insert mode

### ISSUE THREAD

**Issue by gatspy** [vim-dist/webvim#53]
OS: mac osx 10.11.5
I don't know why any key input into `insert mode`

**Comment by krampstudio** [comment]
That's weird. I've never seen this kind of issue. 
How did you install vim and webvim ?

**Comment by gatspy** [comment]
thanks for you reply, i installed macvim and webvim.

**Comment by krampstudio** [comment]
webvim is configured to run in a terminal I think there's some conflicts with MacVim. Do you have the same result when running vim in a terminal ?

**Comment by gatspy** [comment]
I have been using item2. then i test it in terminal. the same issue happened.

**Comment by WebWeave** [comment]
I am having the exact same issue, using iterm2 with oh my zsh

**Comment by WebWeave** [comment]
Already worked it out, this was the problem.
`in insert mode, use jk to switch back to normal mode instead of <esc>`

**Comment by krampstudio** [comment]
Ah, that's what you meant. 
So yes by default, use `jk` to leave the `insert mode`, arrow keys are also disabled in the [hardcore mode](https://github.com/vim-dist/webvim#hardcore-mode). You can disable this mode in the configuration
